### ISSUE TITLE
license問題

### ISSUE THREAD

**Issue by FernandeChant** [RoboRate/TuningTitans#41]
1. 我們的dataset資料來源是這個：https://www.luge.ai/?ref=ruder.io#/luge/dataDetail?id=71
2. Benchmark給GPT-3.5評分的prompt和架構是參考Andrew Ng和Openai合作的課程Evaluation Part II，以及Ted Chen的中文筆記：
(1) Building Systems with the ChatGPT API: https://www.deeplearning.ai/short-courses/building-systems-with-chatgpt/
(2) 中文筆記: 
https://vocus.cc/article/64a6b3d0fd89780001443b86
https://github.com/u8621011/HelloGPT/blob/main/building-system-with-chatgpt-api-06-Evaluation-Part2.ipynb

**Comment by yillkid** [comment]
https://www.luge.ai/?ref=ruder.io#/luge/about    /   该数据仅供研究、学习用途，禁止商用，使用时请注明数据集作者出处；该数据集为NLP贡献者资源整理，所有权归原作者所有，如果侵权，请联系删除。

**Comment by FernandeChant** [comment]
已發出PR
